export const transpile = [
    '@derivean/public',
    '@use-pico/client',
    '@use-pico/server',
    '@use-pico/translator',
    '@use-pico/utils',
    // '@derivean/building',
    // '@derivean/event',
    // '@derivean/game',
    // '@derivean/hero',
    // '@derivean/inventory',
    // '@derivean/item',
    // '@derivean/kingdom',
    // '@derivean/manager',
    // '@derivean/orm',
    // '@derivean/producer',
    // '@derivean/root',
    // '@derivean/server',
    // '@derivean/ui',
];
