# @format

name: Build

on:
    push:
        branches:
            - main

concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4

            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Setup Rust toolchain
              uses: actions-rust-lang/setup-rust-toolchain@v1

            - name: Install wasm-pack
              uses: jetli/wasm-pack-action@v0.4.0
              with:
                  version: "latest"

            # Cache Rust artifacts
            - name: Cache Rust build artifacts
              uses: actions/cache@v4
              with:
                  path: |
                      lib/*/target
                      packages/@derivean/*
                  key: ${{ runner.os }}-rust-${{ hashFiles('lib/*/Cargo.toml', 'lib/*/src/**') }}

            # Cache node modules
            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                  path: |
                      node_modules
                      **/node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('bun.lock', 'package.json') }}

            # Now install JS dependencies
            - name: Install dependencies
              run: bun install

            # Run type checking
            - name: Type check
              run: bun turbo run typecheck

            # Build the application
            - name: Build application
              run: bun turbo run build
